# Generated by Django 3.2 on 2023-10-08 14:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery',
            new_name='Order',
        ),
    ]
